# Generated by Django 3.0.6 on 2022-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFamily', '0003_auto_20220819_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
