# Generated by Django 3.0.6 on 2022-08-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFamily', '0004_auto_20220819_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
