# Generated by Django 3.0.6 on 2022-08-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFamily', '0006_auto_20220825_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='surname',
        ),
    ]
